title: Random Forest-Based Land Use and Land Cover Classification in Brazil's Cerrado
description: Author: Khalil Ganem
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-cayman
